[versions]
agp = "8.9.1"
annotations = "23.0.0"
autoService = "1.1.0"
baoyzLibrary = "1.3.0"
core = "4.6.2"
forms_rt = "7.0.3"
gradle = "8.1.4"
gson = "2.10.1"
hutoolAll = "5.8.20"
javapoet = "1.13.0"
javapoetVersion = "1.14.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.0"
kotlinGradlePlugin = "1.9.0"
libraryVersion = "1.2.0"
lintApi = "31.13.2"
lombok = "1.18.30"
material = "1.10.0"
databindingRuntime = "8.13.1"
library = "3.2.0-alpha11"
mpandroidchart = "v3.1.0"
okhttp = "4.12.0"
prism4jBundler = "2.0.0"
prism4jLanguages = "1.0.0"
prism4jProcessor = "4.6.0"
qmui = "2.0.1"
roomRuntime = "2.8.4"
semver4j = "3.1.0"
swiperefreshlayout = "1.2.0"
uidGenerator = "1.0.5"
ultraPtr = "1.0.11"

[libraries]
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
auto-service = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoService" }
forms_rt = { module = "com.intellij:forms_rt", version.ref = "forms_rt" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hutool-all = { module = "cn.hutool:hutool-all", version.ref = "hutoolAll" }
image = { module = "io.noties.markwon:image", version.ref = "core" }
image-glide = { module = "io.noties.markwon:image-glide", version.ref = "core" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
javapoet-v1141 = { module = "com.squareup:javapoet", version.ref = "javapoetVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
linkify = { module = "io.noties.markwon:linkify", version.ref = "core" }
lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lintApi" }
lint-checks = { module = "com.android.tools.lint:lint-checks", version.ref = "lintApi" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
databinding-runtime = { group = "androidx.databinding", name = "databinding-runtime", version.ref = "databindingRuntime" }
library = { group = "androidx.databinding", name = "library", version.ref = "library" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
prism4j = { module = "io.noties:prism4j", version.ref = "prism4jBundler" }
prism4j-bundler = { module = "io.noties:prism4j-bundler", version.ref = "prism4jBundler" }
prism4j-languages = { module = "io.noties:prism4j-languages", version.ref = "prism4jBundler" }
qmui = { module = "com.qmuiteam:qmui", version.ref = "qmui" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
semver4j = { module = "com.vdurmont:semver4j", version.ref = "semver4j" }
syntax-highlight = { module = "io.noties.markwon:syntax-highlight", version.ref = "core" }
table = { module = "io.noties.markwon:table", version.ref = "core" }
uid-generator = { module = "com.baidu.fsg:uid-generator", version.ref = "uidGenerator" }
ultra-ptr = { module = "in.srain.cube:ultra-ptr", version.ref = "ultraPtr" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

